# 어플리케이션 클러스터에서 실행
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{organization_name}}-prod
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{organization_name}}-sc
parameters:
  server: {{prod_frontend_nas_ip}}
  share: {{prod_frontend_nas_path}}
provisioner: nfs.csi.k8s.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: {{organization_name}}-prod
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |-
    {
        "auths": {
            "{{image_registry}}": {
                "username":"{{harbor_robot_id}}",
                "password":"{{harbor_robot_pw}}",
                "auth": "{{harbor_robot_auth}}"
            }
        }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-tls
  namespace: {{organization_name}}-prod
type: kubernetes.io/tls
stringData:
  tls.crt: |
    {{wildcard_prod_ssl_crt|indent(4)}}

  tls.key: |
    {{wildcard_prod_ssl_key|indent(4)}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{organization_name}}-prod
  name: {{organization_name}}-prod-app-cm-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "deployments", "configmaps","secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{organization_name}}-prod-app-cm-role-binding
  namespace: {{organization_name}}-prod
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{organization_name}}-prod
roleRef:
  kind: Role
  name: {{organization_name}}-prod-app-cm-role
  apiGroup: rbac.authorization.k8s.io
