apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    tekton.dev/categories: CLI
    tekton.dev/displayName: kustomize cli
    tekton.dev/pipelines.minVersion: 0.17.0
    tekton.dev/platforms: linux/amd64
    tekton.dev/tags: cli
  labels:
    app.kubernetes.io/version: "0.1.1"
    hub.tekton.dev/catalog: tekton
  name: kustomize-cli
  namespace: tekton-catalog
spec:
  description: This task is the generic kustomize CLI task which can be used to run
    all kinds of kustomize commands
  params:
  - default: ""
    name: CONTEXT_DIR
    type: string
  - default: kustomize $@
    description: The kustomize CLI script to run
    name: SCRIPT
    type: string
  - default:
    - help
    description: The kustomize CLI arguments to run
    name: ARGS
    type: array
  - default: registry.k8s.io/kustomize/kustomize:v5.0.1
    description: kustomize wrapper image
    name: IMAGE
    type: string
  steps:
  - args:
    - $(params.ARGS)
    computeResources: {}
    image: $(params.IMAGE)
    name: kustomize
    script: |
      #!/usr/bin/env sh

      [[ "$(workspaces.kubeconfig-dir.bound)" == "true" ]] && \
      [[ -f $(workspaces.kubeconfig-dir.path)/kubeconfig ]] && \
      export KUBECONFIG=$(workspaces.kubeconfig-dir.path)/kubeconfig

      $(params.SCRIPT)

    workingDir: $(workspaces.source.path)/$(params.CONTEXT_DIR)
  workspaces:
  - name: source
    optional: true
  - name: kubeconfig-dir
    optional: true
