apiVersion: v1
kind: ConfigMap
metadata:
  name: {{application_name}}-cm
data:
  application.yaml: |
    deployed:
      NODE_NAME: ${NODE_NAME:}
      NODE_IP: ${NODE_IP:}
      NAMESPACE: ${NAMESPACE:}
      POD_NAME: ${POD_NAME:}
      POD_IP: ${POD_IP:}
      JAVA_OPTS: ${JAVA_OPTS:}
    server:
      port: 8080
      servlet:
        context-path: /api
    spring:
      datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:test
        username: backend
        password: backend
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
          ddl-auto: create-drop