apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"name":"cicdbot"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"admin"},"subjects":[{"kind":"ServiceAccount","name":"cicdbot","namespace":"petclinic-cicd"}]}
  creationTimestamp: "2026-07-09T03:41:55Z"
  name: cicdbot
  resourceVersion: "917578"
  uid: 60823ca3-17c1-466c-a54c-ade038cf5d49
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: cicdbot
  namespace: petclinic-cicd
