apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- configmap.yaml
patches:
- target:
    kind: Service
    name: {{application_name}}-svc
  patch: |-
    kind: Service
    metadata:
      name: {{application_name}}-svc
      annotations:
        TCP-80.loadbalancer.nhncloud/listener-protocol: "HTTP"
        loadbalancer.nhncloud/loadbalancer-name: "{{dev_lb_name}}" # 수정
    spec:
      loadBalancerIP: "{{dev_lb_ip}}" # 수정
- target:
    kind: Deployment
    name: {{application_name}}-dp
  patch: |-
    kind: Deployment
    metadata:
      name: {{application_name}}-dp
    spec:
      template:
        metadata:
        spec:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app: {{application_name}}
                  topologyKey: kubernetes.io/hostname
                weight: 1
          containers:
          - name: {{application_name}}-con
- target:
    kind: PersistentVolumeClaim
    name: {{application_name}}-data-pvc
  patch: |-
    kind: PersistentVolumeClaim
    metadata:
      name: {{application_name}}-data-pvc
    spec:
      resources:
        requests:
          storage: 1Gi
      storageClassName: {{organization_name}}-sc
- target:
    kind: PersistentVolumeClaim
    name: {{application_name}}-log-pvc
  patch: |-
    kind: PersistentVolumeClaim
    metadata:
      name: {{application_name}}-log-pvc
    spec:
      resources:
        requests:
          storage: 5Gi
      storageClassName: {{organization_name}}-sc
namespace: {{organization_name}}-dev
commonLabels:
  app: {{application_name}}
images:
- name: {{application_name}}
  newName: {{image_registry}}/{{organization_name}}-dev/{{organization_name}}/{{application_name}}
  newTag: latest