# tekton 관련 설정 커스텀
---
# harbor의 ca인증서
# 변경시 tekton-ctr 재실행
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
  name: config-registry-cert
  namespace: tekton-pipelines
data:
  # Registry's self-signed certificate
  cert: |
    {{harbor_ca|indent(4)}}

---
# tekton 기능 최적화 설정
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
  name: feature-flags
  namespace: tekton-pipelines
data:
  await-sidecar-readiness: "false"
  coschedule: pipelineruns
  disable-affinity-assistant: "true"
  disable-creds-init: "false"
  enable-api-fields: beta
  enable-cel-in-whenexpression: "false"
  enable-param-enum: "false"
  enable-provenance-in-status: "true"
  enable-step-actions: "false"
  enable-tekton-oci-bundles: "false"
  enforce-nonfalsifiability: none
  keep-pod-on-cancel: "false"
  require-git-ssh-secret-known-hosts: "false"
  results-from: termination-message
  running-in-environment-with-injected-sidecars: "true"
  send-cloudevents-for-runs: "false"
  set-security-context: "false"
  trusted-resources-verification-no-match-policy: ignore
---
# tekton task pod 글로벌 설정 (파이프라인실행시 생성될 task 파드의 배치 노드)
  # dns 관련 설정 추가 가능
  # dns host alias 설정
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
  name: config-defaults
  namespace: tekton-pipelines
data:
  default-pod-template: |
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
{%- for node in node_selector_list %}
              - {{node}}
{%- endfor %}
    securityContext:
      fsGroup: 65532