apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  labels:
    app: {{application_name}}
    env: {{env_menu}}
    type: build
  name: {{application_name}}-{{env_menu}}-build-tt
  namespace: {{organization_name}}-cicd
spec:
  params:
  - name: git-host-url
  - name: code-repo-org
  - name: code-repo-name
  - name: code-revision
  - name: code-branch
  resourcetemplates:
  - apiVersion: tekton.dev/v1
    kind: PipelineRun
    metadata:
      labels:
        app: {{application_name}}
        env: {{env_menu}}
        type: build
      generateName: {{application_name}}-{{env_menu}}-build-pr-
      namespace: {{organization_name}}-cicd
    spec:
      params:
      - name: git-host-url
        value: {{gitea_domain}}
      - name: code-repo-org
        value: $(tt.params.code-repo-org)
      - name: code-repo-name
        value: $(tt.params.code-repo-name)
      - name: code-repo-url
        value: $(params.git-host-url)/$(params.code-repo-org)/$(params.code-repo-name).git
      - name: code-revision
        value: $(tt.params.code-revision)
      - name: java-version
        value: "17"
      - name: build-profile
        value: {{env_menu}}
      - name: artifact-find-pattern
        value: build/libs/*.jar
      - name: artifact-rename
        value: ""
      - name: skip-code-test
        value: "false"
      - name: skip-code-analysis
        value: "true"
      - name: skip-code-artifact
        value: "false"
      - name: skip-build-trigger
        value: "true"
      - name: app-env
        value: {{env_menu}}
      - name: app-name
        value: $(params.code-repo-name)
      pipelineRef:
        params:
        - name: kind
          value: pipeline
        - name: name
          value: build-gradle-library
        - name: namespace
          value: tekton-catalog
        resolver: cluster
      taskRunTemplate:
        serviceAccountName: cicdbot
      timeouts:
        pipeline: 1h0m0s
      workspaces:
      - name: shared-data
        persistentVolumeClaim:
          claimName: cicdvol-shared-local-pvc
        subPath: $(params.code-repo-name)
      - name: gitconfig
        secret:
          secretName: cicdbot-gitconfig-secret
      - name: ssl-ca-directory
        secret:
          secretName: cicdssl-cacerts-secret
      - name: gradle-settings
        secret:
          secretName: cicdbot-nexus-secret
      - name: gradle-local-repo
        persistentVolumeClaim:
          claimName: cicdvol-shared-local-pvc
        subPath: .gradle-local-repo
      - name: sonar-credentials
        secret:
          secretName: cicdbot-sonarqube-secret
      - name: kubeconfig
        secret:
          secretName: cicdbot-kubeconfig-secret
