# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: {{application_name}}-data-pvc
# spec:
#   accessModes:
#   - ReadWriteMany
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: {{organization_name}}-sc
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: {{application_name}}-log-pvc
# spec:
#   accessModes:
#   - ReadWriteMany
#   resources:
#     requests:
#       storage: 5Gi
#   storageClassName: {{organization_name}}-sc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{application_name}}-dp
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    spec:
      imagePullSecrets:
      - name: regcred
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: {{application_name}}-con
        image: {{application_name}}
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1001
          runAsNonRoot: true
          runAsUser: 1001
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: NODE_NAME
          valueFrom: {fieldRef: {fieldPath: spec.nodeName}}
        - name: NODE_IP
          valueFrom: {fieldRef: {fieldPath: status.hostIP}}
        - name: NAMESPACE
          valueFrom: {fieldRef: {fieldPath: metadata.namespace}}
        - name: POD_NAME
          valueFrom: {fieldRef: {fieldPath: metadata.name}}
        - name: POD_IP
          valueFrom: {fieldRef: {fieldPath: status.podIP}}
        # - name: JAVA_OPTS_APPEND
        #   value: "-XX:InitialRAMPercentage=25 -XX:MaxRAMPercentage=50"
        - name: JAVA_OPTS_APPEND
          value: "-Djava.io.tmpdir=/app/tmp -Dlogpath=/app/logs -Dhostname=$(POD_NAME)"
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 1000m
            ephemeral-storage: 10Gi
            memory: 2048Mi
          requests:
            cpu: 500m
            ephemeral-storage: 2Gi
            memory: 1024Mi
        volumeMounts:
        - mountPath: /app/data
          name: data
        - mountPath: /app/logs
          name: log
        - mountPath: /app/tmp
          name: tmp
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{application_name}}-data-pvc
      - name: log
        persistentVolumeClaim:
          claimName: {{application_name}}-log-pvc
      - name: tmp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    TCP-80.loadbalancer.nhncloud/listener-protocol: "HTTP"
    loadbalancer.nhncloud/apply-subnet-host-routes: "true"
    loadbalancer.nhncloud/proxy-protocol: "true"
    service.beta.kubernetes.io/openstack-internal-load-balancer: "true" #사설 대역대시
    loadbalancer.nhncloud/loadbalancer-name: "LB-int-dev-{{application_name}}"
  name: {{application_name}}-svc
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.84.111
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: http
    name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
---
# apiVersion: autoscaling/v2beta2
# kind: HorizontalPodAutoscaler
# metadata:
#  name: {{application_name}}-hpa
# spec:
#   maxReplicas: 10 #최대 레플리카 수
#   minReplicas: 2  #최소 레플리카 수
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: {{application_name}}-dp
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 50 #평균 CPU 사용량이 50% 이상인 경우 Scale Out 이하인 경우 Scale In
#   - type: Resource
#     resource:
#       name: memory
#       target:
#         type: Utilization
#         averageUtilization: 50 #평균 MEMORY 사용량이 50% 이상인 경우 Scale Out 이하인 경우 Scale In