apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
- configmap.yaml
- rollout.yaml
patches:
- target:
    kind: Deployment
    name: {{application_name}}-dp
  patch: |-
    kind: Deployment
    metadata:
      name: {{application_name}}-dp
    spec:
      template:
        metadata:
        spec:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app: {{application_name}}
                  topologyKey: kubernetes.io/hostname
                weight: 1
          containers:
          - name: {{application_name}}-con
            env:
            - name: JAVA_OPTS
              value: "-Dfile.encoding=UTF-8 -Dspring.profiles.active=stg"
            resources:
              limits:
                cpu: 1000m
                ephemeral-storage: 5Gi
                memory: 1024Mi
              requests:
                cpu: 500m
                ephemeral-storage: 1Gi
                memory: 512Mi       
- target:
    kind: PersistentVolumeClaim
    name: {{application_name}}-data-pvc
  patch: |-
    kind: PersistentVolumeClaim
    metadata:
      name: {{application_name}}-data-pvc
    spec:
      resources:
        requests:
          storage: 1Gi
      storageClassName: {{organization_name}}-sc
- target:
    kind: PersistentVolumeClaim
    name: {{application_name}}-log-pvc
  patch: |-
    kind: PersistentVolumeClaim
    metadata:
      name: {{application_name}}-log-pvc
    spec:
      resources:
        requests:
          storage: 5Gi
      storageClassName: {{organization_name}}-sc
namespace: {{organization_name}}-stg
commonLabels:
  app: {{application_name}}
images:
- name: {{application_name}}
  newName: {{image_registry}}/{{organization_name}}-stg/{{organization_name}}/{{application_name}}
  newTag: latest