apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: deploy-argocd-app-setup-syncwait
  namespace: tekton-catalog
spec:
  description: |
    This Pipeline for argocd app deploy.
  params:
  - name: git-host-url
    default: "{{gitea_domain}}"
    type: string
  - name: code-repo-org
    default: sample
    type: string
  - name: code-repo-name
    default: sample-backend
    type: string
  - name: code-repo-url
    default: $(params.git-host-url)/$(params.code-repo-org)/$(params.code-repo-name).git
    type: string
  - name: target-cluster
    default: dev
    type: string
  - name: deploy-cluster
    default: https://kubernetes.default.svc
    type: string
  - name: app-env
    default: dev
    type: string
  - name: app-namespace
    default: sample-dev
    type: string
  - name: app-name
    default: $(params.code-repo-name)
    type: string
  - name: skip-app-sync
    default: "false"
    type: string
  - name: skip-zap-scan
    default: "true"
    type: string
  - name: zap-scan-url
    default: https://www.yourdomain.com
    type: string
  - name: zap-scan-script
    default: |
      set +e
      printf "# ZAP Scanning Log"
      printf '\n\n```\n\n'
      zap-baseline.py -t $(params.zap-scan-url) -w report.md
      printf "ZAP Scan completed with exit code $?."
      printf '\n\n```\n\n'
      cat /zap/wrk/report.md
      HIGH_RISK_COUNT=$(grep -m 1 "| High |" /zap/wrk/report.md | cut -d'|' -f3 | tr -d ' ')
      exit $HIGH_RISK_COUNT
    type: string    
  - name: cicd-repo-org
    default: $(params.code-repo-org)-cicd
    type: string
  - name: cicd-repo-name
    default: $(params.code-repo-name)-$(params.app-env)
    type: string
  - name: cicd-repo-url
    default: $(params.git-host-url)/$(params.cicd-repo-org)/$(params.cicd-repo-name).git
    type: string
  - name: cicd-revision
    default: main
    type: string
  - name: argocd-secret
    default: cicdbot-argocd-$(params.target-cluster)-secret
    type: string
  - name: cicd-auto-tag
    default: $(tasks.cicd-fetch.results.cicd-auto-tag-prefix)$(context.pipelineRun.name)
    type: string
  - name: working-pr-dir
    default: $(context.pipelineRun.name)
    type: string
  tasks:
  - displayName: CICD Repo Fetch
    name: cicd-fetch
    params:
    - name: gitInitImage
      value: "{{image_registry}}/nnd/tekton-cicd/git-init:v0.40.2-tz"
    - name: crtFileName
      value: ca-certificates.crt
    - name: sslVerify
      value: "false"
    - name: deleteExisting
      value: "true"
    - name: subdirectory
      value: $(params.working-pr-dir)/$(params.cicd-repo-name)
    - name: url
      value: $(params.cicd-repo-url)
    - name: revision
      value: $(params.cicd-revision)
    taskRef:
      kind: Task
      params:
      - name: kind
        value: task
      - name: name
        value: git-clone
      - name: namespace
        value: tekton-catalog
      resolver: cluster
    workspaces:
    - name: output
      workspace: shared-data
    - name: basic-auth
      workspace: gitconfig
    - name: ssl-ca-directory
      workspace: ssl-ca-directory
  - displayName: ArgoCD App Setup
    name: argocd-appsetup
    params:
    - name: IMAGE
      value: "{{image_registry}}/nnd/tekton-cicd/argocd:v2.11.3"
    - name: SCRIPT
      value: |
        argocd login "$ARGOCD_SERVER" $ARGOCD_OPTS --username="$ARGOCD_USERNAME" --password="$ARGOCD_PASSWORD"
        argocd proj create $(params.app-namespace) -d "*,*" -s "*"
        argocd repo add --project $(params.app-namespace) $(params.cicd-repo-url) --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD --insecure-skip-server-verification
        argocd app create $(params.app-name)-$(params.app-env) --project $(params.app-namespace) --repo $(params.cicd-repo-url) --revision $(params.cicd-revision) --path . --dest-server $(params.deploy-cluster) --dest-namespace $(params.app-namespace) --upsert
        argocd app set $(params.app-name)-$(params.app-env) --revision $(params.cicd-revision)
        argocd app get $(params.app-name)-$(params.app-env)
    - name: SECRET
      value: $(params.argocd-secret)
    runAfter:
    - cicd-fetch
    taskRef:
      kind: Task
      params:
      - name: kind
        value: task
      - name: name
        value: argocd-cli
      - name: namespace
        value: tekton-catalog
      resolver: cluster
  - displayName: ArgoCD App Sync
    name: argocd-appsync
    when:
    - input: $(params.skip-app-sync)
      operator: in
      values:
      - "false"
    params:
    - name: IMAGE
      value: "{{image_registry}}/nnd/tekton-cicd/argocd:v2.11.3"
    - name: SCRIPT
      value: |
        argocd login "$ARGOCD_SERVER" $ARGOCD_OPTS --username="$ARGOCD_USERNAME" --password="$ARGOCD_PASSWORD"
        argocd app sync $(params.app-name)-$(params.app-env) --revision $(params.cicd-revision) --async && argocd app wait $(params.app-name)-$(params.app-env) --sync --health --timeout 600
    - name: SECRET
      value: $(params.argocd-secret)
    runAfter:
    - argocd-appsetup
    taskRef:
      kind: Task
      params:
      - name: kind
        value: task
      - name: name
        value: argocd-cli
      - name: namespace
        value: tekton-catalog
      resolver: cluster
  - displayName: CICD Repo Tag(#deployed) push
    name: cicd-tagpush
    when:
    - input: $(params.skip-app-sync)
      operator: in
      values:
      - "false"
    params:
    - name: CONTEXT_DIR
      value: $(params.working-pr-dir)/$(params.cicd-repo-name)
    - name: BASE_IMAGE
      value: "{{image_registry}}/nnd/tekton-cicd/chainguard-git:2.43.0"
    - name: CRT_FILENAME
      value: ca-certificates.crt
    - name: USER_HOME
      value: /home/git
    - name: GIT_USER_NAME
      value: cicdbot
    - name: GIT_USER_EMAIL
      value: cicdbot@example.com
    - name: GIT_SCRIPT
      value: |
        DEPLOYED_TAG=$(cat README.md)#$(params.cicd-auto-tag)
        git fetch --prune --prune-tags -f && git tag --list '*#*' | xargs -r git push origin --delete
        git fetch --prune --prune-tags -f && git tag --list --sort=-version:refname | tail -n +11 | xargs -r git push origin --delete
        git fetch --prune --prune-tags -f && git tag $DEPLOYED_TAG $(git rev-parse --short HEAD)
        git push origin $DEPLOYED_TAG
    retries: 3
    runAfter:
    - argocd-appsync
    taskRef:
      kind: Task
      params:
      - name: kind
        value: task
      - name: name
        value: git-cli
      - name: namespace
        value: tekton-catalog
      resolver: cluster
    workspaces:
    - name: source
      workspace: shared-data
    - name: basic-auth
      workspace: gitconfig
    - name: ssl-ca-directory
      workspace: ssl-ca-directory
  - displayName: OWASP ZAP Scan
    name: zap-scan
    when:
    - input: $(params.skip-app-sync)
      operator: in
      values:
      - "false"
    - input: $(params.skip-zap-scan)
      operator: in
      values:
      - "false"
    params:
    - name: IMAGE
      value: harbor.yourdomain.com/library/zaproxy/zap-stable:2.16.0
    - name: SCRIPT
      value: |
        $(params.zap-scan-script)
    runAfter:
    - argocd-appsync
    taskRef:
      kind: Task
      params:
      - name: kind
        value: task
      - name: name
        value: zap-scan
      - name: namespace
        value: tekton-catalog
      resolver: cluster      
  finally:
  - displayName: Cleanup Policy
    name: cleanup-policy
    params:
    - name: SCRIPT
      value: |
        find $(workspaces.source.path) -mindepth 1 -maxdepth 1 -type d -name "$(params.working-pr-dir)" | xargs -r rm -rf
        tkn pipelinerun delete --force --keep 0 --all $1 -n $(context.pipelineRun.namespace)
        tkn pipelinerun list $1 -n $(context.pipelineRun.namespace)
        echo $1
    - name: ARGS
      value:
      - --label app=$(params.app-name),env=$(params.app-env),type=deploy,tekton.dev/pipeline!=$(params.app-name)-$(params.app-env)-deploy-pr
    taskSpec:
      metadata: {}
      params:
      - name: SCRIPT
        type: string
      - name: ARGS
        type: array
      spec: null
      steps:
      - args:
        - $(params.ARGS)
        computeResources: {}
        image: "{{image_registry}}/nnd/tekton-cicd/tkn:v0.12.0"
        name: tkn
        script: |
          if [ "$(workspaces.kubeconfig.bound)" = "true" ] && [ -e $(workspaces.kubeconfig.path)/kubeconfig ]; then
            export KUBECONFIG="$(workspaces.kubeconfig.path)"/kubeconfig
          fi
          eval "$(params.SCRIPT)"
      workspaces:
      - name: source
      - name: kubeconfig
    workspaces:
    - name: source
      workspace: shared-data
    - name: kubeconfig
      workspace: kubeconfig
  workspaces:
  - name: shared-data
  - name: gitconfig
  - name: ssl-ca-directory
  - name: kubeconfig